<?php

declare(strict_types=1);

/*
 * Symfony Scheduler regressions for the #[AsCronTask] wiring on
 * TelegramDailySummaryCommand, run against a disposable MySQL container
 * (see compose.yaml) — never the shared dev database.
 *
 * Covered behaviors:
 *  - wiring: exactly one task is registered on the "default" schedule, with
 *    the expected cron expression and command line (no Kernel.php changes
 *    are involved; FrameworkBundle wires this natively once
 *    symfony/scheduler is installed)
 *  - the "0 22 * * *" trigger always resolves to 22:00:00 UTC, including
 *    across DST boundaries and regardless of the ambient PHP timezone
 *  - no immediate execution on startup: the trigger never fires just
 *    because the worker started before or exactly at/after 22:00 UTC
 *  - a due message generated by the REAL scheduler (Schedule +
 *    MessageGenerator, not a manually constructed RunCommandMessage)
 *    reaches the real command and the fake Telegram transport
 *  - a Telegram delivery failure surfaces as an exception; it is never
 *    silently swallowed
 *  - TELEGRAM_ENABLED=false means the real generated message never reaches
 *    the transport, and the command still reports success
 */

require '/app/vendor/autoload.php';

use App\Kernel;
use App\Monolog\Telegram\InterfaceTelegramTransport;
use App\Tests\Monolog\FakeTelegramTransport;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Tools\SchemaTool;
use Symfony\Component\Clock\Clock;
use Symfony\Component\Clock\MockClock;
use Symfony\Component\Console\Exception\RunCommandFailedException;
use Symfony\Component\Console\Messenger\RunCommandMessage;
use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\Messenger\Exception\HandlerFailedException;
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Component\Scheduler\Generator\MessageGenerator;
use Symfony\Component\Scheduler\ScheduleProviderInterface;
use Symfony\Component\Scheduler\Trigger\CronExpressionTrigger;

const TEST_DATABASE = 'scheduler_cron';
const CRON_EXPRESSION = '0 22 * * *';
const COMMAND_LINE = 'gardenhub:telegram:daily-summary --hours=24';

$failures = 0;

function check(bool $condition, string $label): void
{
    global $failures;
    if ($condition) {
        echo "  PASS  $label\n";
    } else {
        echo "  FAIL  $label\n";
        ++$failures;
    }
}

/**
 * A Kernel that exposes test-only public aliases for the exact services
 * needed to observe the real, container-wired Scheduler apparatus, and
 * swaps the real Telegram transport for an in-memory fake. Mirrors the
 * pattern used by MigrationKernel in tests/mqtt-lifecycle/.
 */
final class SchedulerTestKernel extends Kernel
{
    public function __construct(private readonly string $cacheSuffix)
    {
        parent::__construct('dev', true);
    }

    public function getProjectDir(): string
    {
        return '/app';
    }

    public function getCacheDir(): string
    {
        return '/tmp/gardenhub-scheduler-cron/cache-'.$this->cacheSuffix;
    }

    public function getLogDir(): string
    {
        return '/tmp/gardenhub-scheduler-cron/log-'.$this->cacheSuffix;
    }

    protected function build(ContainerBuilder $container): void
    {
        parent::build($container);

        // config/services.yaml (including its when@test InterfaceTelegramTransport
        // override) is loaded AFTER Kernel::build() runs, so registering the fake
        // transport alias here directly would just get clobbered by it. A compiler
        // pass runs after all config loading, so it applies last and wins.
        $container->addCompilerPass(new class implements CompilerPassInterface {
            public function process(ContainerBuilder $container): void
            {
                $container->register('test.fake_telegram_transport', FakeTelegramTransport::class)->setPublic(true);
                $container->setAlias(InterfaceTelegramTransport::class, 'test.fake_telegram_transport')->setPublic(true);
                $container->setAlias('test.messenger.default_bus', 'messenger.default_bus')->setPublic(true);
                // Not public by default; this is the real "default" schedule
                // synthesized by AddScheduleMessengerPass from the #[AsCronTask]
                // attribute — no custom schedule provider class is registered.
                $container->setAlias('test.scheduler_provider_default', 'scheduler.provider.default')->setPublic(true);
            }
        });
    }
}

/**
 * Refuses to touch schema/data unless BOTH: running inside the isolated
 * test Compose file, AND actually connected to its disposable database.
 */
function assertIsolatedTestDatabase(EntityManagerInterface $entityManager): void
{
    if ('1' !== getenv('GARDENHUB_LIFECYCLE_TESTS')) {
        throw new RuntimeException('Run only with the isolated test Compose file.');
    }

    $database = $entityManager->getConnection()->getDatabase();
    if (TEST_DATABASE !== $database) {
        throw new RuntimeException('Refusing to modify a non-test database.');
    }
}

/**
 * Boots a fresh SchedulerTestKernel with the given environment variable
 * overrides applied first. Each distinct set of overrides gets its own
 * cache directory so the container is genuinely recompiled with the new
 * values (env var changes alone do not bust Symfony's container cache).
 */
function bootKernel(string $cacheSuffix, array $envOverrides = []): ContainerInterface
{
    foreach ($envOverrides as $key => $value) {
        putenv("{$key}={$value}");
        $_ENV[$key] = $value;
        $_SERVER[$key] = $value;
    }

    $kernel = new SchedulerTestKernel($cacheSuffix);
    $kernel->boot();

    return $kernel->getContainer();
}

function ensureSchema(ContainerInterface $container): void
{
    /** @var EntityManagerInterface $entityManager */
    $entityManager = $container->get('doctrine')->getManager();
    assertIsolatedTestDatabase($entityManager);

    $schemaTool = new SchemaTool($entityManager);
    $metadata = $entityManager->getMetadataFactory()->getAllMetadata();
    $schemaTool->updateSchema($metadata);
}

function utc(string $time): \DateTimeImmutable
{
    return new \DateTimeImmutable($time, new \DateTimeZone('UTC'));
}

/**
 * Builds a fresh MessageGenerator against the REAL Schedule/RecurringMessage/
 * CronExpressionTrigger wired by AddScheduleMessengerPass — never a manually
 * constructed RunCommandMessage. One instance per scenario keeps checkpoint
 * state isolated between scenarios.
 */
function makeGenerator(ScheduleProviderInterface $provider): MessageGenerator
{
    return new MessageGenerator($provider, 'default', new Clock());
}

/**
 * Polls a generator as of a frozen instant. A generator's first-ever poll
 * establishes its checkpoint baseline AT that instant (mirroring a real
 * worker's startup: it never retroactively fires for runs already due
 * before it started) — so, to observe a due message, the SAME generator
 * must be polled again after the due time has passed relative to that
 * baseline, exactly like a long-running worker's poll loop.
 */
function pollScheduler(MessageGenerator $generator, \DateTimeImmutable $now): array
{
    Clock::set(new MockClock($now));

    return iterator_to_array($generator->getMessages(), false);
}

function test_wiring_registers_exactly_one_cron_task(ContainerInterface $container): void
{
    echo "Scenario: wiring\n";
    /** @var ScheduleProviderInterface $provider */
    $provider = $container->get('test.scheduler_provider_default');
    $messages = $provider->getSchedule()->getRecurringMessages();

    check(1 === count($messages), 'exactly one task is registered on the default schedule');

    $recurringMessage = $messages[array_key_first($messages)];
    check(CRON_EXPRESSION === (string) $recurringMessage->getTrigger(), 'the cron expression is "0 22 * * *"');
    check(
        str_contains((string) $recurringMessage->getProvider(), COMMAND_LINE),
        'the scheduled command line is "gardenhub:telegram:daily-summary --hours=24"'
    );
}

function test_next_run_is_always_22_00_utc_across_dst_changes(): void
{
    echo "Scenario: 22:00 UTC next-run correctness, including across DST changes\n";
    $trigger = CronExpressionTrigger::fromSpec(CRON_EXPRESSION, timezone: 'UTC');

    // The ambient PHP timezone is deliberately set to one that observes
    // DST: if the trigger leaked the ambient zone instead of using the
    // explicit 'UTC' passed above, these assertions would fail around the
    // EU DST boundaries below.
    $previousTimezone = date_default_timezone_get();
    date_default_timezone_set('Europe/Paris');

    try {
        $cases = [
            '2026-01-15 08:00:00' => 'mid-winter',
            '2026-03-28 10:00:00' => 'day before the EU spring-forward change',
            '2026-03-29 23:30:00' => 'the EU spring-forward day itself',
            '2026-07-01 12:00:00' => 'mid-summer',
            '2026-10-24 10:00:00' => 'day before the EU fall-back change',
            '2026-10-25 23:30:00' => 'the EU fall-back day itself',
        ];

        foreach ($cases as $instant => $label) {
            $next = $trigger->getNextRunDate(utc($instant));
            check(
                '22:00:00' === $next->setTimezone(new \DateTimeZone('UTC'))->format('H:i:s'),
                "next run after {$instant} ({$label}) is 22:00:00 UTC"
            );
        }
    } finally {
        date_default_timezone_set($previousTimezone);
    }
}

function test_no_immediate_execution_on_startup(): void
{
    echo "Scenario: no immediate execution on startup\n";
    $trigger = CronExpressionTrigger::fromSpec(CRON_EXPRESSION, timezone: 'UTC');

    $justBefore = $trigger->getNextRunDate(utc('2026-09-21 21:59:59'));
    check(
        '2026-09-21 22:00:00' === $justBefore->format('Y-m-d H:i:s'),
        'starting just before 22:00 UTC waits until later the same day, it does not fire immediately'
    );

    $atDue = $trigger->getNextRunDate(utc('2026-09-21 22:00:00'));
    check(
        '2026-09-22 22:00:00' === $atDue->format('Y-m-d H:i:s'),
        'starting exactly at 22:00 UTC does not re-fire immediately; the next run is the following day'
    );

    $justAfter = $trigger->getNextRunDate(utc('2026-09-21 22:00:01'));
    check(
        '2026-09-22 22:00:00' === $justAfter->format('Y-m-d H:i:s'),
        'starting just after 22:00 UTC waits for the next day, it does not fire immediately'
    );
}

function test_real_scheduler_generated_message_reaches_telegram(ContainerInterface $container): void
{
    echo "Scenario: a due message generated by the real scheduler reaches Telegram\n";
    /** @var ScheduleProviderInterface $provider */
    $provider = $container->get('test.scheduler_provider_default');
    /** @var FakeTelegramTransport $transport */
    $transport = $container->get('test.fake_telegram_transport');
    /** @var MessageBusInterface $bus */
    $bus = $container->get('test.messenger.default_bus');

    $generator = makeGenerator($provider);

    $atStartup = pollScheduler($generator, utc('2026-09-21 00:00:00'));
    check([] === $atStartup, 'nothing is generated immediately at worker startup');

    $notYetDue = pollScheduler($generator, utc('2026-09-21 21:59:59'));
    check([] === $notYetDue, 'no message is generated before the 22:00 UTC due time');

    $due = pollScheduler($generator, utc('2026-09-21 22:00:01'));
    check(1 === count($due), 'exactly one due message is generated by the real scheduler at 22:00 UTC');

    $message = $due[0];
    check($message instanceof RunCommandMessage, 'the generated message is a real RunCommandMessage, not a hand-built one');
    check(str_contains($message->input, COMMAND_LINE), 'the generated message runs the daily-summary command with --hours=24');

    $transport->calls = [];
    $bus->dispatch($message);
    check(1 === count($transport->calls), 'dispatching the real generated message sends exactly one Telegram message');
}

function test_delivery_failure_is_not_swallowed(ContainerInterface $container): void
{
    echo "Scenario: a Telegram delivery failure surfaces, it is not silently swallowed\n";
    /** @var ScheduleProviderInterface $provider */
    $provider = $container->get('test.scheduler_provider_default');
    /** @var FakeTelegramTransport $transport */
    $transport = $container->get('test.fake_telegram_transport');
    /** @var MessageBusInterface $bus */
    $bus = $container->get('test.messenger.default_bus');

    $transport->armToThrow();
    $generator = makeGenerator($provider);
    pollScheduler($generator, utc('2026-09-22 00:00:00'));
    $due = pollScheduler($generator, utc('2026-09-22 22:00:01'));
    check(1 === count($due), 'a fresh due message is generated for the failure scenario');

    $threw = false;
    try {
        $bus->dispatch($due[0]);
    } catch (HandlerFailedException $e) {
        $threw = true;
        // Exceptions are keyed by handler service id, not by numeric index.
        $wrapped = array_values($e->getWrappedExceptions())[0] ?? null;
        check($wrapped instanceof RunCommandFailedException, 'the failure surfaces as a RunCommandFailedException, not silently as success');
    }
    check($threw, 'dispatching the due message propagates the delivery failure instead of swallowing it');
}

function test_disabled_telegram_never_sends(): void
{
    echo "Scenario: TELEGRAM_ENABLED=false means no send\n";
    $container = bootKernel('disabled', ['TELEGRAM_ENABLED' => 'false']);

    /** @var ScheduleProviderInterface $provider */
    $provider = $container->get('test.scheduler_provider_default');
    /** @var FakeTelegramTransport $transport */
    $transport = $container->get('test.fake_telegram_transport');
    /** @var MessageBusInterface $bus */
    $bus = $container->get('test.messenger.default_bus');

    $generator = makeGenerator($provider);
    pollScheduler($generator, utc('2026-09-23 00:00:00'));
    $due = pollScheduler($generator, utc('2026-09-23 22:00:01'));
    check(1 === count($due), 'a due message is still generated by the real scheduler when Telegram is disabled');

    $bus->dispatch($due[0]);
    check([] === $transport->calls, 'the fake transport is never invoked when TELEGRAM_ENABLED=false');
}

$mainContainer = bootKernel('main', [
    'TELEGRAM_ENABLED' => 'true',
    'TELEGRAM_BOT_TOKEN' => 'test-token',
    'TELEGRAM_CHAT_ID' => 'test-chat',
]);
ensureSchema($mainContainer);

test_wiring_registers_exactly_one_cron_task($mainContainer);
test_next_run_is_always_22_00_utc_across_dst_changes();
test_no_immediate_execution_on_startup();
test_real_scheduler_generated_message_reaches_telegram($mainContainer);
test_delivery_failure_is_not_swallowed($mainContainer);
test_disabled_telegram_never_sends();

echo "\n";
if ($failures > 0) {
    echo "{$failures} assertion(s) FAILED.\n";
    exit(1);
}

echo "All assertions passed.\n";
exit(0);
